### ISSUE TITLE
Crashing game (probably when active playlist is empty)

### ISSUE THREAD

**Issue by thejulfor** [fudgeu/playlist#2]
When I created new playlist, I didn't add new songs and started playing random song from default list. When it ended, my minecraft crashed with this error:

Error: java.lang.NullPointerException: Cannot invoke "com.fudgeu.playlist.objects.PlaylistObj.getGameLeadTime()" because "playlist" is null

**Comment by fudgeu** [comment]
Hey, I'm unable to recreate this issue on my end. Is there anymore info. Is there any other info you can give? From what it seems from that error message, that type of error should only occur when you just loaded into the game/new dimension. Also, if possible, can you upload the full crash report? Thank you!

**Comment by wu4x** [comment]
I also encountered this bug, to recreate:
1. Stop playing music
2. Go into another dimension or disconnecting from server/world
3. It crashes because of a nullpointer exception

[crash-2022-07-13_20.11.43-client.txt](https://github.com/fudgeu/playlist/files/9104865/crash-2022-07-13_20.11.43-client.txt)
n

**Comment by fudgeu** [comment]
Fixed, an updated version will be releasing later today with many other bug fixes
