### ISSUE TITLE
What does the Time Variance setting mean

### ISSUE THREAD

**Issue by TechPro424** [fudgeu/playlist#24]
What does the time variance setting mean?
(I think the "time between songs" setting is the one that solves my previous issue #22, correct me if I'm wrong pls)

![image](https://user-images.githubusercontent.com/86620085/201262638-e951aae1-3438-4cfa-9c5f-ed792e10ab12.png)

**Comment by DeadbushCarrot** [comment]
Set both to 1 or 2 seconds

**Comment by DeadbushCarrot** [comment]
Oh Time varies option is like the amount for next song to play so if your Time between songs is to like 5 secs and the time varies is set to 20 it will randomly choses a time between 5 and 20 secs

**Comment by fudgeu** [comment]
Almost, lol, I should honestly remove the option since it doesn't provide much use, but:
- Time between songs defines, well, how much time there will be between songs
- Time variance defines how much 'Time between songs' varies, so if your time between songs is 60 and variance is 10, then in reality the amount of time between songs will be a random number between 50 and 70 (so time between songs +/- random value within time variance)
