### ISSUE TITLE
Fixed loop once icon

### ISSUE THREAD

**Issue by DeadbushCarrot** [fudgeu/playlist#25]
I fixed the loop once icon so the 2 dots are a actual 1

**Comment by DeadbushCarrot** [comment]
I forgot to send it lol
[Playlist gui textures.zip](https://github.com/fudgeu/playlist/files/10461695/Playlist.gui.textures.zip)

**Comment by fudgeu** [comment]
I'll look into adding these for 1.3.0 :)
I personally think I like the monochrome theme for the icons better, but I'll likely make it a setting to switch between monochrome and colored icons in the settings
(And ofc I'll credit you for the icons, once I find the space to put credits lol)

**Comment by DeadbushCarrot** [comment]
I made the colored ones in my free time but if you want I could make the new textures for you if you want?

**Comment by fudgeu** [comment]
Oh no, there's nothing wrong with them! I was just saying that I think plain white icons match the theme of the UI better, but that's just my personal preference. Some people might like the colorful icons better so that's why I'll make it a toggle in the settings :)
If you want to update your icons though, there's nothing stopping you lol

**Comment by DeadbushCarrot** [comment]
I mean like new designs like new icons like this 
![speaker](https://user-images.githubusercontent.com/109874700/214181683-6175449c-c3b4-4880-bde5-252c7e41b5c5.png)
