### ISSUE TITLE
Ability to import custom tracks

### ISSUE THREAD

**Issue by MacchuPicchu3** [fudgeu/playlist#39]
This mod is the closest I've found to meeting my ideal music experience in Minecraft, with one major exception : I can't find a way to import custom tracks (Volume Alpha has tons of bangers that went unused in the base game). Your response to a previous ticket indicated that this was possibly planned? I'd love to know when that might happen.

In addition, **there are a number of design/UI/interface issues that could be improved** based on my experience. I would love to talk to you about these over Discord, and I'd be happy to draw up detailed solutions myself. Please do reach out to me at MacchuPicchu#8655

Again, I am very impressed with your work on this mod, and I would even be willing to donate a modest sum of money if it would help development.

**Comment by fudgeu** [comment]
Hi! Yes - the ability to add custom tracks is planned, and will probably be seen in update 1.4. It's just been a low priority since I never intended the mod to have this ability, but due to popular demand I'll be looking to add it very soon.

The next update (1.3) is actually going to see some parts of the UI changed, as I am working on a rather big UI library at the moment (which is why it is taking a while, along with work, school, etc). Once complete, it will also be spun off as a separate library mod for others to use. Though, for 1.3, it should be built out enough to introduce an entirely new settings menu with it, and maybe a new song info screen. Version 1.4 will see the rest of the interface changed.

If you have any suggestions though, you can leave them here for now! I'm currently on a trip so I unfortunately don't have much time to check my Discord actively.

As for donations, I thought I had linked my Kofi page in the ReadMe but this issue made me realize I never actually linked it anywhere, lol. I'll go ahead and update that now. Donations are always appreciated, thank you!

**Comment by MacchuPicchu3** [comment]
Okay, well, it seems like you have lots of changes coming down the pipeline, which is great to hear! I can only comment on what I see with the current version. I have a lot to say, but hopefully it's useful feedback.

### [1] Tooltips & accessibility

I have to be totally honest here: the lack of tooltips makes this mod a bit of a nightmare for new users. You've tried your best to make things understandable with a variety of icons, but everything still takes way too much trial-and-error to figure out, and it really diminishes the user experience, especially at the beginning. Adding tooltips would go a long way towards alleviating that.

### [2] Menu screen scaling 

The mod's menu screen does not scale properly at higher GUI scalings, which in my experience is at a GUI scaling of 3 (or Auto). As you can see in the screenshot below, all of the elements are colliding with each other, and even though everything works correctly, it's really unpleasant to look at.

![GUI scale issue](https://user-images.githubusercontent.com/105882768/224814186-d0d48bba-7a06-4015-9149-86c2d58fee68.png)

### [3] Blank playlist names

It's possible to create playlists with no name at all. I imagine this is unintended, especially since this makes them totally invisible in the left sidebar.

### [4] Missing playlist option icon texture

If you right-click a song that is in a playlist _while also_ having selected a dimensional sub-category (e.g. Overworld, End), then an option to "Remove from Category" appears. Trouble is, its icon appears to be missing, as you can see in the screenshot below.

![missing texture](https://user-images.githubusercontent.com/105882768/224815992-410df5ac-ee9f-44a2-941b-7b3f4d57a0ab.png)

### [5] Volume slider is weird

Not if you use it as intended, since that part works great and is really cool. The weird part is what happens if you left-click the volume button. Inexplicably, this stops the current song's playback . . . ? Why??

My best guess is that this was supposed to be a mute function, but it obviously doesn't do that. Even weirder, once you click on the volume button, the volume icon switches to something whose texture is missing, as with [4].

### [6] Time controls

One of the greatest parts of Minecraft's music has nothing to do with the music itself, and that's the time in between tracks, which you have aptly named _interludes_. This allows the different songs to float in and out of the player's attention in a beautiful way.

Thankfully, your mod **does** preserve this key aspect of the vanilla game . . . the problem is that the user wouldn't know it by looking. The only way to adjust the time and the time variance between tracks is to right-click an already-created playlist and visit its options menu. At the very least, I think you should add those two fields to the "create playlist" screen, so that users are more likely to be aware of this functionality and its customizability.

### [7]  Default playlist icon

The icon you created for Default playlists is, to my eyes at least, not very intuitive and also a bit cluttered (since you've tried to mash together two symbols into a small space). If I were you I'd consider experimenting with something else, maybe a star shape?

### [8] Playlist "play" option

If I right click a playlist in the sidebar and select the "Play" option, nothing happens, at least as far as I can tell. I cranked the time down to 20±10 seconds, and still got nothing.

### [9] Interlude doesn't appear

The music player won't update to show that the music is in an interlude after a song has finished _unless_ the player exits and reenters the mod's menu.

### [10] Playback inconsistencies

Let's talk about the music playback. As I mentioned previously, one of the best parts about Minecraft's music is the fact that there are long breaks in between tracks. This allows the game (and the player's mind) room to breathe.

If I load up a world, music playback works exactly as it should. I can consult the mod's menu to see that my default playlist is Playing (with a bright green button), and the music player will let me know that I'm at an interlude.

But it doesn't work so well as soon as I stop playback, because if I then press the "Play" button, it will immediately start playing a song. That's not what I usually want. Worse still, if I hit the "Next" button, it again immediately starts playing another track. The end result is that there's no way (as far as I can tell) to get the music player to return to an interlude, which is what I would most often want it to do when I'm done messing with playback.

A few possible solutions to this would be:
- Make the "Play" and the "Next" buttons begin with an interlude by default; pressing the "Next" button during an interlude would actually start playing another song.
- Add the above feature, but as a toggle instead of by default.
- Add an "Cut to Interlude" button to the music player; a good spot might be centered right below the "Stop Playback" button.

### [11] Playback terminology

To continue the above discussion about playback, I want to briefly discuss terminology. Consider the following statements.

- A Playlist is a group of songs that can be played together. When I begin to Play a playlist, it immediately begins playback of one of the playlist's songs. While Playing, there is no gap between songs.

This sentence describes how the words _Playlist_, _Play_, and _Playing_ mean in the context of most music-playing software that you and I are familiar with. But your mod is a bit different. Playing one of your mod's playlists doesn't immediately begin playback (or at least it shouldn't), and unlike most music players, there is indeed an important gap in between songs. 

In a word, music playback in Minecraft is a lot less like a playlist in the normal sense and a lot more like a background process. For that reason, I think you should consider using words other than _play_ and _playing_ for this mod – maybe _start_ and _running_ or something more descriptive, like _begin ambient playback_ and _playing ambience_. You could even rename the playlists to "ambient playlists", for example, although admittedly that might be a bit clunky.

Adding to the confusion is the fact that you can use the mod both to play tracks one after the other (like a normal playlist) and also ambiently (like in Minecraft, with interludes in between tracks), and yet, these two very different functionalities both display as _Play_ and _Playing_. I feel like a distinction is in order.

### [12] "All songs" section

My first recommendation here is to rename the "All Songs" section to the _Library_. Just seems a bit more elegant.

Now onto my concerns about the section itself. As a new user, it is easy to be confused by the Library and the default playlist. At first glance, they look exactly the same, and even after spending some more time with it, they still feel almost identical. I'm guessing the major difference is that a playlist will actually play music while you're playing the game, interludes included, while the Library won't (I could be wrong there though). In a word, I find it difficult to understand the purpose of the Library section.

I have two suggestions:
- There is a green "Playing" indicator that appears in the side bar next to either the Library or a playlist when it is playing music – but _ONLY_ if you pressed the "Play" button and not if you double-clicked a song in the list, which . . . why?? Regardless of how you choose to resolve that particular inconsistency, I feel that the indicator should be a bit more prominent.
- The column that shows whether or not a particular track is a creative track, an aquatic track, a biome-dependent track, etc. etc. shows up in the Library section. Why is that useful information here? Aren't you meant to use the Playlists to actually play music during gameplay? If so, I would consider removing this column from the Library.

### [13] Weight column

One of the best features of your mod is the ability to weight tracks differently. This is exactly what I was looking for, because I want to hear Lena Raine's music slightly less often than C418's (it's still very good music, it's just not as ambient as C418's, imo). 

But in order to build a playlist that is weighted the way I want, it would be very helpful to see that information displayed as a column. You could enrich the mod further by also using the tooltip suggestion from [1] – imagine if hovering over a song's weight displayed the song's weight, the total weight pool, and a percentage approximation, i.e. "1/23 (4.3%)". I'd certainly find this useful, but you could always make it a toggle if you think most users wouldn't.

### [14] Special conditions

By this I mean the the fact that a track can be biome-dependant, aquatic-only, creative-only, etc. etc. This is probably the most complex feature in the mod, and there are a lot of ease-of-use questions that arise from its inclusion. Let's take this screenshot as a first example.

![conditions](https://user-images.githubusercontent.com/105882768/224870926-a671591a-8c91-4517-a6a5-3f2aba803b20.png)

It's not immediately clear what the "Categories" section is communication to me, the player. How am I supposed to interpret the list of different biomes? Is it "All overworld biomes, but more commonly in forest/jungle/lush caves"? Is it "Only certain overworld biomes, namely forest/jungle/lush caves"? I think it's the second option, but it's really not obvious to the user at all.

Things will get even more complicated if, as you indicated in a different ticket, you intend to let the player assign different weights to different biomes _for each individual track_. Which you absolutely should do, by the way – it's just that it will require a bit of reorganization. I have some ideas as to how you could do that. If you're interested, let me know and I will elaborate in another comment.

### [15] Marketing

The last issue I have with this mod has nothing to with the mod itself but rather with the way it is presented to prospective users. As a starting point, here is what I see for your mod when I search for it on Modrinth.

![Screen Shot 2023-03-13 at 4 22 46 PM](https://user-images.githubusercontent.com/105882768/224835513-539c272c-8e62-4305-a640-1379e9f1c335.png)

Let's start with the name of the mod itself, Playlist. I will preface my critique by saying that the name Playlist _does make sense_ given that playlists are kind of the organizing principle of the mod. But man, when I first read this . . . "Playlist" is such a generic-sounding name that I am immediately bored to death. Worse, I tend to associate the word "Playlist" with something like "relatively insignificant side feature of a larger piece of software". This is a shame because a name like this MASSIVELY UNDERSELLS what your mod is truly capable of. It deserves better.

As for alternatives – one option is to pick a name that suggests something grand and sweeping, like "BetterMusic" or "MusicOverhaul". Your mod would definitely be worthy of a name like this. If that makes you skeptical, you should know that there's a mod out there called "Musica" that just adds extra music discs to the game, and another called "OstOverhaul" that just adds a few new tracks to the normal pool of background music.

Another option (the one I prefer personally) is to name your mod to something random but evocative – there's a reason that Sodium and Lithium aren't named PerformanceTweaks or some other uninteresting name. This kind of name sticks better. To take inspiration from your username, here's a suggestion: rename it to "Brownie". Simply put, brownies are tasty, and I can guarantee that your mod will catch more people's attention and be remembered a lot more than it would be with the name "Playlist".

The next issue is the logo artwork. Honestly, it looks really low effort, as if you just grabbed it from a random game's resource files. If that's the case, then no judgement – I just think that your mod is good enough to deserve better. Go contact an artist and commission them for an original logo! I did that for all three of my data packs; it really wasn't very expensive and the result was completely worth it. You could, for instance, have them make a logo of a brownie in the shape of a quarter note :)

Last but not least: the mod's description is extremely weak, to the point that the description makes the mod sound worse than it actually is!! Try something like:

- [ ] **BROWNIE:** Minecraft's music, played to your taste. Create fully customized ambient playlists, including biome-dependent playback and classic vanilla breaks between songs.

See what I did with the first sentence? ;) Jokes aside: I believe it's very important to put the interludes between the songs front and center, because frankly, that's one of the few reasons anyone would bother downloading your mod instead of just having their favorite music playback software running in the background. Oh, and once the functionality is added, this blurb should obviously mention the ability to import custom songs, too.

**Comment by DeadbushCarrot** [comment]
God damn you were not kidding also Please to god set Modrinth to oled or dark mode pls in the setting! spare your eyes

**Comment by DeadbushCarrot** [comment]
there's no texture error for me I just looked

**Comment by DeadbushCarrot** [comment]
The next issue is the logo artwork. Honestly, it looks really low effort, as if you just grabbed it from a random game's resource files. If that's the case, then no judgement – I just think that your mod is good enough to deserve better. Go contact an artist and commission them for an original logo! I did that for all three of my data packs; it really wasn't very expensive and the result was completely worth it. You could, for instance, have them make a logo of a brownie in the shape of a quarter note :)

Ok for this one I have redrawn the logo cause I knew it could be better like here'
![play](https://user-images.githubusercontent.com/109874700/224894451-d9072661-c413-4203-bb83-d1bd613ca0ba.png)
s the redrawn logo he hasn't updated it yet

**Comment by MacchuPicchu3** [comment]
I hope I didn't overdo it :(

**Comment by fudgeu** [comment]
No, sorry! I just don't do a great job of checking here very often haha - I'm pretty busy working on a lot of things in life unfortunately.

But to address everything:

**[1]** Yup, tooltips have been something I've been meaning to do for a while - I just wanted to wait until I got the chance to implement them in a way that's easily scalable everywhere and not a pain in the ass, lol (which I now am, with the UI library I'm working on). It's likely they wont be used in 1.3.0, since I'm only transitioning a few things to the new UI library for now, but I plan on transferring the entire UI to the new library by 1.4

**[2]** Also aware of - and also to be taken care of with the new UI :)

**[3]** Gotcha - I'll make sure that wont be possible in 1.3, thanks!

**[4]** Haha yeah I noticed that shortly after publishing the mod - for some reason the file went missing while I was switching computers. Already fixed though on my end :)

**[5]** That's actually vanilla behavior, weirdly enough - if you go into your settings, set music volume to zero, and then turn it back up, any music that was playing will be gone. I didn't do anything to prevent that from happening for the sake of keeping things vanilla, but it wouldn't be hard to prevent that behavior if wanted!

**[6]** True - I'll go ahead and do that, thanks!

**[7]** Yeah, I had a hard time figuring out what icon could best represent _default_ lol, but a star icon would totally make sense, don't know what I didn't think of that before haha

**[8]** You're right - noted!

**[9]** Yup - that should be fixed with the next update!

**[10]** A toggle was something I actually had planned and completely forgot about for some reason. The framework for it is already there, so I'll go ahead and put it in for the next update, thanks for reminding me lol

**[11]** This was a choice I had to make while implementing the buttons, and the issue with it is that it really comes down to personal preference - since there are people, like you, who would like it to start off/skip to an interlude, and others who would prefer to keep skipping through until they find a song they want to play. Obviously I catered to the latter, but I'll go ahead an add a toggle that allows you to start on/skip to an interlude. I don't want to force people onto one option since I now know there are parties for both, and I don't want to add more clutter to the media controls, so I think a toggle in settings would be the best option :)

**[12]** Terminology is something I had an issue with in this mod, and unfortunately it used to be worse. I do understand what you are saying though, and it has been something I've been thinking about ever since people wanted the inclusion of custom songs. The solution I've thought of, at least for now, is to introduce two types of 'playlists' - one that resembles and plays just like a real playlist on a music service would, and one that resembles more of the default Minecraft experience. The details are still scarce and it's something that I'll both figure out once I get around to implementing it and am open to suggestions for. A large part of the difficulty is trying to keep everything simple while still providing a lot of flexibility. Though, I'm sure something will come up eventually that can adhere to that principle, and I'll keep your ideas in mind once I do start messing around with that more

**[13]** So, there were two reasons I wanted to include the 'All Songs' section:

- Make it easy to play the default Minecraft music experience, as all songs in there are set up to their vanilla defaults and cannot be edited.
- Allow you to form new playlists out of it and serve as a reference point. In case someone wants to add a song to a new playlist that has been deleted from all of their own playlists, it can always be found in the 'All Songs' section.
Also, the default playlist that comes out of the box is identical to the 'All Songs' playlist (therefore representing the default Minecraft music experience), except it can be edited. Though, I will consider the idea of renaming it to 'Library', since you are right, it does sound more elegant lol.

As for the suggestions:
- For the green bar on the side, currently what happens is when clicking on a song, it plays that song and then returns to the playlist that was active before (instead of full-on switching to that playlist). This was my personal preference, though you are fair to point out that it is a bit odd. Likely, I'll switch it over the behavior that you and most others would expect, and maintain the ability to play one-off songs outside of a playlist via the 'Add to Queue' option (much in the same way that Spotify works).
- The categories that show up on the right side are there because, again, the 'All Songs' playlist is meant more of a reference that contains, well, _all songs_ as well as their default options and categories.

**[14]** Sure, I'll consider it - it would likely roll out when the entire UI is converted to the new library :)

**[15]** So, I've been meaning to write a simple wiki for a while now, mainly to explain how categories work. But yes, your guess is right, the way that screenshot can be read is:
_"This song can play in the menu and overworld, but when in the overworld, only in the Forest, Jungle, and Lush Cave biomes."_
And yes, I'm aware of the added complexity individual weights per biome may add, lol - but I think I have a few ideas to get help simplify it

**[16]** So, to start off - marketing is not something I'm focusing too much, it's not my goal to get this mod on the top of any lists or anything, lol. It's more of a (rather big) side project that I more just find enjoying to work on.

For the name, I actually did want to steer away from a name like 'MusicOverhaul', Its more a matter of personal preference than anything. An evocative or simple name is more my style, and I sorta just picked 'Playlist' as the code name while in dev and stuck with it. I'm not _toooo_ keen on changing the name, I guess its not too late, but if something more evocative comes up in my mind and I like it, I'll go ahead and change it lol.

For the logo, it is indeed a 5 second Photoshop job. Like I said, I'm not huge on marketing this mod, and I'm not too much of an artist either, but Carrot did provide a nicer, upgraded version that I've been meaning to include in the next major update! So, at least there's that, lol. If the mod blows up suddenly to the point of tens or hundreds of thousands, though, I might commission a new logo and full set of assets to add to the pages' READMEs.

And I'll also take a note on the description - I wanted to keep it short but descriptive, but maybe I'll give a little more thought into it the next time I update the pages :)

Thanks for all the suggestions though and bugs you pointed out!

---

For what its worth, heres a demo of the UI library currently being worked on:

<img src="https://i.imgur.com/kvT8rPu.gif" />

Its React.JS-inspired, and uses XML and JSON for layouts/styling. Definitely a whole lot easier than hardcoding the positions and dimensions of every single element, and a lot easier to implement more complex features with, lol

**Comment by DeadbushCarrot** [comment]
Um the Colorful Icons should not be a switch cause I have like 3 versions so it could be like the accent color button but if pressed it changes the name to what preset it is so it would be Colorful, Consistent colorful and Playlist plus also If possible can I get sent the textures folder so I can update the color button presets

**Comment by fudgeu** [comment]
Oh no don’t worry, that menu is not at all finished yet. I’m mostly playing around with thing and there’s still a lot of stuff that need to be adjusted and added

I’ll send the icons when I’m able to sometime tomorrow though :)

**Comment by DeadbushCarrot** [comment]
Thanks also I tested the Colored icons and fixed them up and the logo again. I was just pointing out a solution also tomorrow ill send the updated icons

**Comment by MacchuPicchu3** [comment]
Yay! So happy to hear all of this!

Yeah I'd forgotten that [5] was vanilla behavior, my bad :P

When you review your description – try to think of why a user would be looking for a music-related mod. What would they be looking for that they couldn't get in a mainstream music playing software? The way I see it, it'll generally be one of two things: 

1) User is looking for a way to listen to music with Minecraft's pacing (i.e., with the interludes), or
2) User is looking for a way to control where in the game specific music is played  (i.e. biome-dependent, menu music, etc.).

I strongly feel that the presence of these two features _need_ to be stated explicitly in Playlist's description/summary. Don't assume your users know what you mean when you say "control Minecraft's music". Tell them your mod has the features they're most likely to be searching for, and they'll investigate!

Anyways, thanks for everything you've done. Can't wait to see the mod's progression from here on out! Best of luck with everything irl as well

**Comment by fudgeu** [comment]
The way that I've thought about phrasing it is 'Control _how_ Minecraft's music plays' - or something like that. Its short and simple and implies that its not just a way to select whatever song you want, but that you have complete control over the existing ambient-like music.

Though, its important not to forget that there is also a large group of users who only care about being able to play music in Minecraft in the more traditional sense, like a music service like Spotify. So, you know, gotta cater to both lol

Thank you tho! I'm really hoping to get the next update out as soon as possible

**Comment by DeadbushCarrot** [comment]
Hey if possible can I have the updated textures for playlist so I can update the colored textures

**Comment by fudgeu** [comment]
[gui.zip](https://github.com/fudgeu/playlist/files/11166703/gui.zip)

Sorry for the wait - here they are though!
I've had more time recently to work on the mod thankfully, and I think I'm just about done with the first version of the UI library. Currently converting some menus to the new UI library, gonna add a few extra features, and the next version should be out!

**Comment by DeadbushCarrot** [comment]
Ok thanks. I got to update them now!

**Comment by DeadbushCarrot** [comment]
What is some of the new textures?

**Comment by DeadbushCarrot** [comment]
yeah I don't see any new ones

**Comment by fudgeu** [comment]
You're right - I don't think I did end up adding any new ones for this update, its been a while 😅

But, I think just about the only thing left for this update is to implement that ability to actually switch between icon sets, and maybe another bug fix or two

**Comment by DeadbushCarrot** [comment]
Ok then well then I didn't even need to update the icons so here's the icons I updated then 
[Playlist icons.zip](https://github.com/fudgeu/playlist/files/11266539/Playlist.icons.zip)

**Comment by DeadbushCarrot** [comment]
Did you get the updated icons?

**Comment by fudgeu** [comment]
Yup! They've been implemented and are fully functional, thanks!

**Comment by DeadbushCarrot** [comment]
your welcome

**Comment by fudgeu** [comment]
1.3 is out now! I'm going to go ahead and close this for now, but feel free to continue some discussion here or preferably open new individual tickets about the stuff we've talked about in here :)

**Comment by JeremyStarTM** [comment]
It's sad to see that this feature hasn't been implemented as but was instead marked "closed as completed", which is a complete lie.

First of all I have decompiled the 1.3.0 version and have found nothing that is responsible for loading custom tracks, which is sad. But the second thing is that the feature request was "closed as completed" and in the closing comment @fudgeu even stated that "1.3 is out now!" which **can** suggest that the feature has been implemented. This is not how you run a issue tracker.

![fudgeu's comment](https://github.com/fudgeu/playlist/assets/53786253/05c5e6fd-676a-402e-9440-23d321d6a3c7)

Thank you for wasting a hour of my time "debugging" this.

**Comment by Felix14-v2** [comment]
Very polite.

**Comment by JeremyStarTM** [comment]
I was a little bit angry while writing this comment... maybe not the best mood for it.

**Comment by JeremyStarTM** [comment]
Changed it.

**Comment by MacchuPicchu3** [comment]
I didn't request custom tracks in this ticket at all, though, because it had already been brought up in previous ones.

**Comment by MacchuPicchu3** [comment]
> Hi! Yes - the ability to add custom tracks is planned, and will probably be seen in update 1.4.

From post #2

**Comment by JeremyStarTM** [comment]
Yeah, I have missed that. But that does not change the fact that you should keep a feature request open as long as it is not implemented.

**Comment by Felix14-v2** [comment]
Well, just open another issue for tracking purposes, because this one lost its main topic and has been closed after solving other problems described above.
Trust me, expressing anger does not contribute to achieving your goal in any way. So just don't worry, be happy :)

**Comment by JeremyStarTM** [comment]
> Well, just open another issue for tracking purposes

I'll do that.

> Trust me, expressing anger does not contribute to achieving your goal in any way. So just don't worry, be happy :)

Yeah, expressing anger isn't really a great idea as I've [pointed out already](https://github.com/fudgeu/playlist/issues/39#issuecomment-1666850170).
