### ISSUE TITLE
[bug] Playlists aren't saved

### ISSUE THREAD

**Issue by wu4x** [fudgeu/playlist#4]
Issue:
Creating a new playlist creates a perfectly fine working playlist. 
Except, when closing and reopening the game the playlist is suddenly gone.
The playlist folder in .minecraft is completely empty

**Comment by fudgeu** [comment]
Yup, just an issue with how often playlists are saved - currently they are only saved when you enter the pause screen. Already working on making it more frequent!
If for some reason they still don't save when you enter the pause screen, let me know because that would be a different issue, lol
Thank you!
