### ISSUE TITLE
Incompatibility with Rainbowify

### ISSUE THREAD

**Issue by Afrocntrik** [fudgeu/playlist#9]
![2022-07-12_01 32 06](https://user-images.githubusercontent.com/11052983/180366000-6502ea6f-9c95-4637-abe2-89d1f9f01318.png)

[Rainbowify](https://modrinth.com/mod/rainbowify) link

**Comment by fudgeu** [comment]
Hi! Sorry for the late reply, I just recently came back from vacation and had school start. But otherwise, I'm unable to replicate the bug on my end, is there anything specific you did (e.g. certain settings)?

Even though I haven't been able to replicate it, I believe I know the root cause and implemented some fixes to hopefully let the two mods work a bit better. Though, I can't verify that these fixes worked and can't improve on them until I can either replicate it or let you try out the next version. But hopefully, they did!

Expect the next release sometime very soon :)
